import type { Metadata } from "next";
import { Josefin_Sans, Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/lib/ReduxProvider";

const josefin_sans = Josefin_Sans({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce Cart App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={josefin_sans.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
